language: go
os:
  - linux
  - windows
  - osx
go:
  - "1.13"

install:
  # code lint tools
  - go get -u golang.org/x/lint/golint
  # Install make for windows
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install make; fi

script:
  - make check
  - make build
  - make test

after_success:
  - if [ $TRAVIS_OS_NAME = linux ]; bash <(curl -s https://codecov.io/bash); fi
