name: "Test"

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: [ "1.17", "1.18", "1.19", "1.20", "1" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Test
        run: make test
